app:
  name: love-recycling-go
  port: 8090 # 运行端口
  token:
    expiration: 1440 # token可用时间
    secret: asoufonaosuhfdlkzjxnmojapwkrsjhdvbfkhabsigdinbkjzbfijasdadas
    jwt_blacklist_grace_period: 10 # 黑名单宽限时间
    refresh_grace_period: 1800 #  token 自动刷新宽限时间（秒）
database:
  host: 127.0.0.1 # 数据库ip
  port: 3306 # 数据库端口
  user: root # 数据库用户名
  password: 123456 # 数据库密码
  db_name: love_recycling # 数据库名
  charset: utf8mb4 # 编码格式
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
log:
  level: info # 日志等级
  root_dir: ./storage/logs # 日志根目录
  filename: app.log # 日志文件名称
  format: # 写入格式 可选json
  show_line: true # 是否显示调用行
  max_backups: 3 # 旧文件的最大个数
  max_size: 500 # 日志文件最大大小（MB）
  max_age: 28 # 旧文件的最大保留天数
  compress: true # 是否压缩
redis:
  host: 127.0.0.1
  port: 6379